version: "3.3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - podcast-db
    entrypoint:
      - dotnet
      - backend.dll
    ports:
      - 6001:6001
    expose:
      - '6001'
  podcast-db:
    image: mcr.microsoft.com/mssql/server:2017-CU14-ubuntu
    volumes:
      - podcast-vol:/var/opt/mssql
    environment:
      SA_PASSWORD: "Password1"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
volumes:
  podcast-vol: