USE [master]
GO

/****** Object:  Database [podcast_me]    Script Date: 30.03.2020 14:00:39 ******/
CREATE DATABASE [podcast_me]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'podcast_me', FILENAME = N'/var/opt/mssql/data/podcast_me.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'podcast_me_log', FILENAME = N'/var/opt/mssql/data/podcast_me_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [podcast_me].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [podcast_me] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [podcast_me] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [podcast_me] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [podcast_me] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [podcast_me] SET ARITHABORT OFF 
GO

ALTER DATABASE [podcast_me] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [podcast_me] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [podcast_me] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [podcast_me] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [podcast_me] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [podcast_me] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [podcast_me] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [podcast_me] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [podcast_me] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [podcast_me] SET  DISABLE_BROKER 
GO

ALTER DATABASE [podcast_me] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [podcast_me] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [podcast_me] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [podcast_me] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [podcast_me] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [podcast_me] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [podcast_me] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [podcast_me] SET RECOVERY FULL 
GO

ALTER DATABASE [podcast_me] SET  MULTI_USER 
GO

ALTER DATABASE [podcast_me] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [podcast_me] SET DB_CHAINING OFF 
GO

ALTER DATABASE [podcast_me] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [podcast_me] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [podcast_me] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [podcast_me] SET QUERY_STORE = OFF
GO

ALTER DATABASE [podcast_me] SET  READ_WRITE 
GO


